/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package good_enough_inc;

/**
 *
 * @author swp99
 */
public class Student extends javax.swing.JFrame {

    /**
     * Creates new form Student
     */
    public Student() {
        initComponents();
        setSize(1000, 600);
        getContentPane().setBackground(new java.awt.Color(255,255,255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Plurality = new javax.swing.JFrame();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        Next_Plurality = new javax.swing.JButton();
        jLabel76 = new javax.swing.JLabel();
        Choose_Many = new javax.swing.JFrame();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Return_Many = new javax.swing.JButton();
        Next_Many = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jLabel77 = new javax.swing.JLabel();
        Binary = new javax.swing.JFrame();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Return_Binary = new javax.swing.JButton();
        Next_Binary = new javax.swing.JButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jLabel78 = new javax.swing.JLabel();
        Pref = new javax.swing.JFrame();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Return_Pref = new javax.swing.JButton();
        Submit = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Begin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();

        Plurality.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        Plurality.setPreferredSize(new java.awt.Dimension(980, 590));
        Plurality.setResizable(false);
        Plurality.getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Election Name");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Plurality.getContentPane().add(jLabel4);
        jLabel4.setBounds(399, 21, 227, 27);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Race Information");
        Plurality.getContentPane().add(jLabel5);
        jLabel5.setBounds(399, 105, 227, 35);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Please Select One of the Options Below:");
        Plurality.getContentPane().add(jLabel6);
        jLabel6.setBounds(217, 187, 354, 35);

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton1.setText("Option 1");
        Plurality.getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(458, 224, 79, 25);

        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton2.setText("Option 2");
        Plurality.getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(458, 267, 79, 25);

        jRadioButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton3.setText("Option 3");
        Plurality.getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(458, 310, 79, 25);

        jRadioButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton4.setText("Option 4");
        Plurality.getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(458, 353, 79, 25);

        jRadioButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton5.setText("Option 5");
        Plurality.getContentPane().add(jRadioButton5);
        jRadioButton5.setBounds(458, 396, 79, 25);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setText("Write-In");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        Plurality.getContentPane().add(jTextField1);
        jTextField1.setBounds(485, 439, 176, 23);

        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        Plurality.getContentPane().add(jRadioButton6);
        jRadioButton6.setBounds(458, 441, 25, 21);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/good_enough_inc/L1.JPG"))); // NOI18N
        Plurality.getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 179, 80);

        Next_Plurality.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Next_Plurality.setText("Next");
        Next_Plurality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next_PluralityActionPerformed(evt);
            }
        });
        Plurality.getContentPane().add(Next_Plurality);
        Next_Plurality.setBounds(833, 528, 137, 51);

        jLabel76.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel76.setIcon(new javax.swing.ImageIcon(getClass().getResource("/good_enough_inc/Wildcat.png"))); // NOI18N
        Plurality.getContentPane().add(jLabel76);
        jLabel76.setBounds(0, 0, 960, 580);

        Choose_Many.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        Choose_Many.setResizable(false);
        Choose_Many.getContentPane().setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Election Name");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Choose_Many.getContentPane().add(jLabel8);
        jLabel8.setBounds(399, 21, 227, 27);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Race Information");
        Choose_Many.getContentPane().add(jLabel9);
        jLabel9.setBounds(399, 105, 227, 35);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Please Select As Many of the Options Below:");
        Choose_Many.getContentPane().add(jLabel10);
        jLabel10.setBounds(217, 187, 354, 35);

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField2.setText("Write-In");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        Choose_Many.getContentPane().add(jTextField2);
        jTextField2.setBounds(482, 446, 176, 28);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/good_enough_inc/L1.JPG"))); // NOI18N
        Choose_Many.getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 179, 80);

        Return_Many.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Return_Many.setText("Previous");
        Return_Many.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Return_ManyActionPerformed(evt);
            }
        });
        Choose_Many.getContentPane().add(Return_Many);
        Return_Many.setBounds(10, 518, 137, 50);

        Next_Many.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Next_Many.setText("Next");
        Next_Many.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next_ManyActionPerformed(evt);
            }
        });
        Choose_Many.getContentPane().add(Next_Many);
        Next_Many.setBounds(830, 518, 137, 50);

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox1.setText("Option 1");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        Choose_Many.getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(459, 229, 79, 25);

        jCheckBox2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox2.setText("Option 2");
        Choose_Many.getContentPane().add(jCheckBox2);
        jCheckBox2.setBounds(459, 272, 79, 25);

        jCheckBox3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox3.setText("Option 3");
        Choose_Many.getContentPane().add(jCheckBox3);
        jCheckBox3.setBounds(459, 315, 79, 25);

        jCheckBox4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox4.setText("Option 4");
        Choose_Many.getContentPane().add(jCheckBox4);
        jCheckBox4.setBounds(459, 358, 79, 25);

        jCheckBox5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox5.setText("Option 5");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        Choose_Many.getContentPane().add(jCheckBox5);
        jCheckBox5.setBounds(459, 401, 79, 25);
        Choose_Many.getContentPane().add(jCheckBox6);
        jCheckBox6.setBounds(459, 453, 21, 21);

        jLabel77.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel77.setIcon(new javax.swing.ImageIcon(getClass().getResource("/good_enough_inc/Wildcat.png"))); // NOI18N
        Choose_Many.getContentPane().add(jLabel77);
        jLabel77.setBounds(0, 0, 960, 580);

        Binary.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        Binary.setResizable(false);
        Binary.getContentPane().setLayout(null);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Election Name");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Binary.getContentPane().add(jLabel12);
        jLabel12.setBounds(399, 21, 227, 27);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Race Information");
        Binary.getContentPane().add(jLabel13);
        jLabel13.setBounds(399, 105, 227, 35);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Please Select One of the Options Below:");
        Binary.getContentPane().add(jLabel14);
        jLabel14.setBounds(217, 188, 626, 34);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/good_enough_inc/L1.JPG"))); // NOI18N
        Binary.getContentPane().add(jLabel15);
        jLabel15.setBounds(0, 0, 179, 80);

        Return_Binary.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Return_Binary.setText("Previous");
        Return_Binary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Return_BinaryActionPerformed(evt);
            }
        });
        Binary.getContentPane().add(Return_Binary);
        Return_Binary.setBounds(10, 525, 137, 51);

        Next_Binary.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Next_Binary.setText("Next");
        Next_Binary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next_BinaryActionPerformed(evt);
            }
        });
        Binary.getContentPane().add(Next_Binary);
        Next_Binary.setBounds(816, 524, 137, 52);

        jRadioButton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton7.setText("Yes");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });
        Binary.getContentPane().add(jRadioButton7);
        jRadioButton7.setBounds(442, 246, 53, 31);

        jRadioButton8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton8.setText("No");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });
        Binary.getContentPane().add(jRadioButton8);
        jRadioButton8.setBounds(546, 240, 47, 43);

        jLabel78.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel78.setIcon(new javax.swing.ImageIcon(getClass().getResource("/good_enough_inc/Wildcat.png"))); // NOI18N
        Binary.getContentPane().add(jLabel78);
        jLabel78.setBounds(0, 0, 960, 580);

        Pref.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        Pref.setResizable(false);
        Pref.getContentPane().setLayout(null);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Election Name");
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Pref.getContentPane().add(jLabel16);
        jLabel16.setBounds(399, 21, 227, 27);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Race Information");
        Pref.getContentPane().add(jLabel17);
        jLabel17.setBounds(399, 105, 227, 35);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Please label order of preferance, where lower numbers means most preffered:");
        Pref.getContentPane().add(jLabel18);
        jLabel18.setBounds(166, 187, 626, 35);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/good_enough_inc/L1.JPG"))); // NOI18N
        Pref.getContentPane().add(jLabel19);
        jLabel19.setBounds(0, 0, 179, 80);

        Return_Pref.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Return_Pref.setText("Previous");
        Return_Pref.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Return_PrefActionPerformed(evt);
            }
        });
        Pref.getContentPane().add(Return_Pref);
        Return_Pref.setBounds(10, 519, 137, 50);

        Submit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Submit.setText("Submit Ballot");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        Pref.getContentPane().add(Submit);
        Submit.setBounds(865, 519, 137, 50);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-SELECT AN ITEM-", "Option 1", "Option 2", "Option 3", "Option 4", "Option 5" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        Pref.getContentPane().add(jComboBox1);
        jComboBox1.setBounds(422, 240, 185, 28);

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-SELECT AN ITEM-", "Option 1", "Option 2", "Option 3", "Option 4", "Option 5" }));
        Pref.getContentPane().add(jComboBox2);
        jComboBox2.setBounds(422, 286, 185, 28);

        jComboBox3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-SELECT AN ITEM-", "Option 1", "Option 2", "Option 3", "Option 4", "Option 5" }));
        Pref.getContentPane().add(jComboBox3);
        jComboBox3.setBounds(422, 332, 185, 28);

        jComboBox4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-SELECT AN ITEM-", "Option 1", "Option 2", "Option 3", "Option 4", "Option 5" }));
        Pref.getContentPane().add(jComboBox4);
        jComboBox4.setBounds(422, 378, 185, 28);

        jComboBox5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-SELECT AN ITEM-", "Option 1", "Option 2", "Option 3", "Option 4", "Option 5" }));
        Pref.getContentPane().add(jComboBox5);
        jComboBox5.setBounds(422, 424, 185, 28);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("1.");
        Pref.getContentPane().add(jLabel20);
        jLabel20.setBounds(389, 243, 15, 22);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("2.");
        Pref.getContentPane().add(jLabel21);
        jLabel21.setBounds(389, 289, 15, 22);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setText("3.");
        Pref.getContentPane().add(jLabel22);
        jLabel22.setBounds(389, 335, 15, 22);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setText("4.");
        Pref.getContentPane().add(jLabel23);
        jLabel23.setBounds(389, 381, 15, 22);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setText("5.");
        Pref.getContentPane().add(jLabel24);
        jLabel24.setBounds(389, 427, 15, 22);

        jLabel79.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel79.setIcon(new javax.swing.ImageIcon(getClass().getResource("/good_enough_inc/Wildcat.png"))); // NOI18N
        Pref.getContentPane().add(jLabel79);
        jLabel79.setBounds(0, 0, 960, 580);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jList1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(404, 192, 182, 251);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Available Ballots");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(404, 157, 182, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Student Home Page");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 11, 211, 29);

        Begin.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Begin.setText("Begin Voting");
        Begin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeginActionPerformed(evt);
            }
        });
        getContentPane().add(Begin);
        Begin.setBounds(404, 449, 182, 37);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Please click on a ballot in the list and press 'Begin Voting' to open the ballot to vote.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(42, 95, 893, 29);

        jLabel75.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel75.setIcon(new javax.swing.ImageIcon(getClass().getResource("/good_enough_inc/Wildcat.png"))); // NOI18N
        getContentPane().add(jLabel75);
        jLabel75.setBounds(0, 0, 960, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void Next_PluralityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next_PluralityActionPerformed
        // TODO add your handling code here:
        Choose_Many.setSize(1000, 600);
        Choose_Many.getContentPane().setBackground(new java.awt.Color(255,255,255));
        Choose_Many.setVisible(true);
        Plurality.setVisible(false);
    }//GEN-LAST:event_Next_PluralityActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void Return_ManyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Return_ManyActionPerformed
        // TODO add your handling code here:
        Plurality.setVisible(true);
        Choose_Many.setVisible(false);
    }//GEN-LAST:event_Return_ManyActionPerformed

    private void Next_ManyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next_ManyActionPerformed
        // TODO add your handling code here:
        Binary.setSize(1000, 600);
        Binary.getContentPane().setBackground(new java.awt.Color(255,255,255));
        Binary.setVisible(true);
        Choose_Many.setVisible(false);
    }//GEN-LAST:event_Next_ManyActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void Return_BinaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Return_BinaryActionPerformed
        // TODO add your handling code here:
        Choose_Many.setVisible(true);
        Binary.setVisible(false);
    }//GEN-LAST:event_Return_BinaryActionPerformed

    private void Next_BinaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next_BinaryActionPerformed
        // TODO add your handling code here:
        Pref.setSize(1000, 600);
        Pref.getContentPane().setBackground(new java.awt.Color(255,255,255));
        Pref.setVisible(true);
        Binary.setVisible(false);
    }//GEN-LAST:event_Next_BinaryActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton2.isSelected())
        {
            jRadioButton2.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void Return_PrefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Return_PrefActionPerformed
        // TODO add your handling code here:
        Binary.setVisible(true);
        Pref.setVisible(false);
    }//GEN-LAST:event_Return_PrefActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void BeginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeginActionPerformed
        // TODO add your handling code here:
        Plurality.setSize(1000, 600);
        Plurality.getContentPane().setBackground(new java.awt.Color(255,255,255));
        Plurality.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BeginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Begin;
    private javax.swing.JFrame Binary;
    private javax.swing.JFrame Choose_Many;
    private javax.swing.JButton Next_Binary;
    private javax.swing.JButton Next_Many;
    private javax.swing.JButton Next_Plurality;
    private javax.swing.JFrame Plurality;
    private javax.swing.JFrame Pref;
    private javax.swing.JButton Return_Binary;
    private javax.swing.JButton Return_Many;
    private javax.swing.JButton Return_Pref;
    private javax.swing.JButton Submit;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
